### ISSUE TITLE
Remove ` <!-- svelte-ignore a11y-autofocus --> `

### ISSUE THREAD

**Issue by baseplate-admin** [sssuneeth/CoreProject-V3-UI#101]
https://github.com/sssuneeth/CoreProject-V3-UI/blob/b621297d4bcad2bbeb5bbb44137c3e8479344a28/src/lib/components/shared/search_panel.svelte#L18-L25

**Comment by sssuneeth** [comment]
Its because I need to add `autofocus` it shows warning.
Yea there are other ways

**Comment by baseplate-admin** [comment]
>  Yea there are other ways

use those. Autofocus is deprecated
