### ISSUE TITLE
Rating star icon size issue

### ISSUE THREAD

**Issue by sssuneeth** [sssuneeth/CoreProject-V3-UI#38]
![Screenshot from 2023-04-17 20-25-41](https://user-images.githubusercontent.com/114811070/232524511-91be5e6f-8f1e-4c26-b386-6bff9f64e777.png)

@baseplate-admin 
See this star icon size doesnt support string values only integer values
So we cant use `vw` values here

![Screenshot from 2023-04-17 20-28-49](https://user-images.githubusercontent.com/114811070/232525240-1f4f70f3-50da-4e66-bc22-0d7af631de38.png)

```js
<StarRating
	rating={4.5}
	config={{ size: 20,  fullColor: '#DCD9F7', emptyColor: 'rgb(220, 217, 247, 0.4)' }}
	style={'margin: 0; gap: 5px'}
/>
```

This will be an issue in responsivness

**Comment by baseplate-admin** [comment]
Hmmm. We need to code this component our-self..  You want to? Or i Will take a look

**Comment by baseplate-admin** [comment]
@sssuneeth

**Comment by sssuneeth** [comment]
> Hmmm. We need to code this component our-self.. You want to? Or i Will take a look

Yea I can to this, but I need time
Hmm, If you're free, take a look

**Comment by baseplate-admin** [comment]
>  Hmm, If you're free, take a look

Currently nope. I am making the parser. ( it's killing me lol )

**Comment by sssuneeth** [comment]
> Currently nope. I am making the parser. ( it's killing me lol )

Yea, then I will do it NP

**Comment by baseplate-admin** [comment]
Hey suneeth lets close this for later. Current behavior looks okay to me

**Comment by sssuneeth** [comment]
> Hey suneeth lets close this for later. Current behavior looks okay to me

Yea sure, but we cant avoid this bad guy.
