### ISSUE TITLE
There's a wild sunnyth in our repo

### ISSUE THREAD

**Issue by baseplate-admin** [sssuneeth/CoreProject-V3-UI#44]
Hi, Did you get hacked?

Who put this ? 
![image](https://user-images.githubusercontent.com/61817579/233011841-4a05a5f3-54f9-48ea-b18d-b09710e705ee.png)

**Comment by sssuneeth** [comment]
>Hi, Did you get hacked?
Who put this ?

XD, I couldn't find any other cool and matching profile pic :D
Next I'll add 69 guy DW

**Comment by baseplate-admin** [comment]
>  Next I'll add 69 guy DW

I will give you a star if you add him

**Comment by sssuneeth** [comment]
> I will give you a star if you add him

Now his time to rock! I added his nice pose in profile XD check
