### ISSUE TITLE
Check if `lodash` solves this 

### ISSUE THREAD

**Issue by baseplate-admin** [sssuneeth/CoreProject-V3-UI#48]
Hi,

please dont write functions by yourself. check if `lodash` provides you with this.

https://github.com/sssuneeth/CoreProject-V3-UI/blob/2e4a91acda7e3b09200fba929c2f5d8948686b71/src/lib/components/pages/home/MainHero/LatestEpisodes.svelte#L13

**Comment by sssuneeth** [comment]
Hi there,

> please dont write functions by yourself. check if lodash provides you with this.

Yea, It seems we can use `loadash` for this sorting.
Oky thanks for that.

**Comment by baseplate-admin** [comment]
Feel free to close this issue after you implemented it :)

**Comment by sssuneeth** [comment]
Yea sure :D
