### ISSUE TITLE
Dont do this

### ISSUE THREAD

**Issue by baseplate-admin** [sssuneeth/CoreProject-V3-UI#54]
https://github.com/sssuneeth/CoreProject-V3-UI/blob/2e4a91acda7e3b09200fba929c2f5d8948686b71/src/lib/components/pages/home/MyList/Index.svelte#L1-L56

Don't write `MyList/Index.svelte`
Do `MyList.svelte`

**Comment by sssuneeth** [comment]
>Do MyList.svelte

Yea! I used to think we might have more files inside that folder.
Will remove that :)
