### ISSUE TITLE
Look at this

### ISSUE THREAD

**Issue by baseplate-admin** [sssuneeth/CoreProject-V3-UI#60]
![image](https://user-images.githubusercontent.com/61817579/233891812-ce04b744-cdb4-4e40-b4a1-6c59d6622c82.png)

**Comment by baseplate-admin** [comment]
![image](https://user-images.githubusercontent.com/61817579/233891869-f7f92ae1-75a0-4538-9870-b69d49cc9ba7.png)

**Comment by sssuneeth** [comment]
Yea sure, I said that the popup is only finished.
Need to do that button on hover.
