### ISSUE TITLE
Switch to a better Data structure

### ISSUE THREAD

**Issue by baseplate-admin** [sssuneeth/CoreProject-V3-UI#68]
https://github.com/sssuneeth/CoreProject-V3-UI/blob/375ddc33c08f0c5d7210b0c346853428cc4478b4/src/lib/components/pages/home/main_hero/latest_animes.svelte#L97-L112

Example : 
```typescript
const colors = [
{"color":"bg-error-400"}

]

**Comment by sssuneeth** [comment]
> {"color":"bg-error-400"} and {"boder-color":"bg-error-400"} looks same to me . why make 2 arrays?

Yea I need to, just added for testing
