### ISSUE TITLE
Convert SearchBar to `modal`

### ISSUE THREAD

**Issue by baseplate-admin** [sssuneeth/CoreProject-V3-UI#74]
https://github.com/sssuneeth/CoreProject-V3-UI/blob/aaa7ae1368feb6ccf7e0f36f5d30efe90a0bfe60/src/routes/%2Blayout.svelte#L266-L272

https://github.com/sssuneeth/CoreProject-V3-UI/blob/aaa7ae1368feb6ccf7e0f36f5d30efe90a0bfe60/src/routes/%2Blayout.svelte#L346-L356

https://github.com/sssuneeth/CoreProject-V3-UI/blob/aaa7ae1368feb6ccf7e0f36f5d30efe90a0bfe60/src/routes/%2Blayout.svelte#L430-L514

This is not the right way to do things. Because if you need animations you need to code it yourself.

 Consider switching to [`modals`](https://www.skeleton.dev/utilities/modals)

**Comment by sssuneeth** [comment]
> Because if you need animations you need to code it yourself.

It has blur transition already.
You want that slide up animation?

**Comment by baseplate-admin** [comment]
> It has blur transition already.

Its more about using what skeleton gives us

**Comment by baseplate-admin** [comment]
@sssuneeth

**Comment by sssuneeth** [comment]
Hey there!
Whatsup

**Comment by sssuneeth** [comment]
Hey there!
I'm working on that popup thing, yea will work in search bar after that.

**Comment by baseplate-admin** [comment]
>  I'm working on that popup thing, yea will work in search bar after that.

Did you raise an issue?

**Comment by sssuneeth** [comment]
> This is a bummer 

Yea, we need to wait :)

**Comment by sssuneeth** [comment]
@baseplate-admin Converted to models.
Check now and close this issue if you're okkay
