### ISSUE TITLE
Consider moving all the logics into this file

### ISSUE THREAD

**Issue by baseplate-admin** [sssuneeth/CoreProject-V3-UI#75]
https://github.com/sssuneeth/CoreProject-V3-UI/blob/aaa7ae1368feb6ccf7e0f36f5d30efe90a0bfe60/src/routes/%2Bpage.svelte#L10-L12

Its better to have one large file compared to 100 small ones.

**Comment by sssuneeth** [comment]
Those files are really big.
Are you sure?

**Comment by baseplate-admin** [comment]
Have structure

**Comment by baseplate-admin** [comment]
Any updates on this?
