### ISSUE TITLE
This is not right

### ISSUE THREAD

**Issue by baseplate-admin** [sssuneeth/CoreProject-V3-UI#79]
https://github.com/sssuneeth/CoreProject-V3-UI/blob/41172145023cbc05659c3f4eeb48cce326f3945d/src/routes/%2Blayout.svelte#L477

![image](https://user-images.githubusercontent.com/61817579/234485402-e4032291-2b41-4268-8c80-4f0883c232ab.png)

**Comment by baseplate-admin** [comment]
Fixed?

**Comment by sssuneeth** [comment]
> Fixed?

Noooo, I need 1 week to fix that :)
