### ISSUE TITLE
Configure og for twitter

### ISSUE THREAD

**Issue by sssuneeth** [sssuneeth/CoreProject-V3-UI#83]
Need to configure og for twitter
@baseplate-admin 

![Screenshot from 2023-04-26 23-02-58](https://user-images.githubusercontent.com/114811070/234656678-145dfdab-29bc-471a-9eba-81e97c7e7218.png)

**Comment by baseplate-admin** [comment]
I Don't like elon musk. Hes a bald man

**Comment by sssuneeth** [comment]
> I Don't like elon musk. Hes a bald man

XD, he likes animes

**Comment by baseplate-admin** [comment]
He still is a Bald man
