### ISSUE TITLE
Popup is not working fine on live as in dev env.

### ISSUE THREAD

**Issue by sssuneeth** [sssuneeth/CoreProject-V3-UI#91]
### Current Behavior

Popup is working fine on dev env but when it comes in live, that popup disappears when I hover and move around on trigger div.
And I'm using popup inside a loop, here is the main code

```html
<script lang="ts">
	// skeleton and floating-ui
	import { popup } from '@skeletonlabs/skeleton';
	import type { PopupSettings } from '@skeletonlabs/skeleton';
	import { computePosition, autoUpdate, flip, shift, offset, arrow } from '@floating-ui/dom';
	import { storePopup } from '@skeletonlabs/skeleton';

	storePopup.set({ computePosition, autoUpdate, flip, shift, offset, arrow });

	let popupSettings: PopupSettings = {
		event: 'hover', // event
		target: 'my_list_popup' // data-popup value
	};
</script>

<div>
	<div>
		{#each my_list as anime}
			<div
				use:popup={popupSettings}
			>
				<div>
                                        <!-- trigger code -->
                                </div>
			</div>
                        <div
				data-popup="my_list_popup"
			>
				<!-- popup code -->
				<div class="arrow bg-surface-50" />
			</div>
		{/each}
	</div>
</div>
```

and here is the full code https://pastebin.mozilla.org/nR4kuXHR

[Screencast from 2023-04-26 20-34-04.webm](https://user-images.githubusercontent.com/114811070/234635596-3531c646-bd9f-4cae-b647-275d3fc63cbf.webm)

1st one is the live site and 2nd one is the dev env ( localhost )
The problem is with the 1st one ( live )

**Comment by baseplate-admin** [comment]
Tracking : https://github.com/skeletonlabs/skeleton/issues/1509

**Comment by sssuneeth** [comment]
Decided to use **tippy.js** instead skeleton popup
Currently skeleton popups couldn't meet our requirements so moved to tippy.js for now.

Now popups are as expected, so I'm closing this issue :)
