### ISSUE TITLE
for the love of god change this 

### ISSUE THREAD

**Issue by baseplate-admin** [sssuneeth/CoreProject-V3-UI#96]
https://github.com/sssuneeth/CoreProject-V3-UI/blob/0780df93e9584853a0f224a166418509b846b769/src/routes/user/register/%2Bpage.svelte#L21-L51

**Comment by sssuneeth** [comment]
Yea XD, its not even working fine.

**Comment by sssuneeth** [comment]
@baseplate-admin
here is new update on validation
https://github.com/sssuneeth/CoreProject-V3-UI/blob/8cce2c208ba8c2d71fc033e365825acd757f9e8a/src/routes/user/register/%2Bpage.svelte#L13-L62

It validate form on instant.
server-side validation doesnt match our design pattern.

And also we can do server side validation for _user checking, ..._ something like that.
however we need client-side validation too for **_good user experience_**

**Comment by baseplate-admin** [comment]
Don't use regex

**Comment by sssuneeth** [comment]
> Don't use regex

Oky, give reason
